### ISSUE TITLE
change reports "code=202" 

### ISSUE THREAD

**Issue by KomoriWu** [alexa-samples/alexa-smarthome#37]
Json is right in the Validation Schema. 
However, echo does not have any translation.
很费解，你们为什么没有更多的log提示

**Comment by aszk** [comment]
I'd recommend checking https://developer.amazon.com/en-US/docs/alexa/smarthome/test-live-debug.html if the change report went through. If you still have the same problem, you can https://alexa.design/contactus with discovery response and change report you sent and expected behavior and actual behavior.
