### ISSUE TITLE
Discovery operation is not showing any devices ( not even virtual devices) 

### ISSUE THREAD

**Issue by AnimeshBote** [alexa-samples/alexa-smarthome#69]
I have performed each and every instruction carefully. My endpoints are us-east-1 north America ( Virginia ). When I test my lambda function with .json test-event, It successfully executes the code and display the correct response.But when I enable that skill and try to use it to find out my light device or at least virtual device, it doesn't show anything. It only says no devices found. Please help I have tried everything but it's just not working. When I try to discover any device from Alexa app it doesn't show any log entries but when I test the lambda function with test event and if there is any error then only it is showed in the log. Does it mean my lambda function is not getting called?

**Comment by AnimeshBote** [comment]
Solution : I changed the Endpoint-region to ireland and it worked!!

**Comment by krishnu9** [comment]
How do i change the endpoint-region of a previously created lambda function?

**Comment by AnimeshBote** [comment]
You will have to create a new function. I don't think you can change the endpoints directly.

**Comment by Kasuhikdas** [comment]
I am also having the same problem?what was the skill language English(US) or English(IN)?

**Comment by dievaa** [comment]
The discovery process can potentially fail because of a mismatch between the account's PFM (Preferred market place), the skill locale, and the lambda endpoint region.

For example, if your skill locale includes en-GB, if you want to make the discovery work for GB customers, you should deploy the lambda function also in the eu-west-1 region. If you want to test it, you also have to set the PFM of your dev account to GB.

You can find additional information here: https://developer.amazon.com/en-US/blogs/alexa/device-makers/2023/07/smart-home-discovery-alexa-july-2023
