### ISSUE TITLE
Failed to enable skill for test

### ISSUE THREAD

**Issue by LuForGitHub** [alexa-samples/alexa-smarthome#90]
I was following below instruction to set up a smart home skill:
https://github.com/alexa/alexa-smarthome/wiki/Build-a-Working-Smart-Home-Skill-in-15-Minutes

However, at the test stage, I failed to enable the skill, as I got below error:
 The authorization server returned with an error parameter. Please refer to https://tools.ietf.org/html/rfc6749#section-4.1.2.1 for more details. 

Please advise.  Thanks

**Comment by sebwills** [comment]
I had the same problem. By using the Chrome dev tools, and turning on its option 'Auto open DevTools for popups', I was able to capture the error parameter in the auth popup, which was something like 'Invalid scope'.  Taking a guess, I tried changing the scope in the security profile I'd set up to "profile:user_id" (from [here](https://developer.amazon.com/docs/login-with-amazon/customer-profile.html))  instead of "profile", and then it worked!

Not sure why "profile" wasn't accepted - can anyone shed any light? (I'm in the UK, in case that affects security/privacy options).

**Comment by rouport** [comment]
One issue I had was not actually enabling my created security profile to log in with amazon. If you navigate to the [amazon developer console](https://developer.amazon.com/home.html) and click Login with Amazon, you can enable your security profile by providing a Consent Privacy Notice URL. I just used amazon's: https://www.amazon.com/gp/help/customer/display.html?nodeId=468496.

**Comment by sebwills** [comment]
Thanks @rouport, that was very helpful!

**Comment by faengelm** [comment]
Hi rouport. That also fixed my problem

**Comment by pixelatedpic** [comment]
> Thanks @rouport, that was very helpful!

i have done the same but still not working for me

**Comment by pixelatedpic** [comment]
@rouport anyway i figured it out and the skill enabled. but how do i know if this works? i tried Alexa, turn on switch and it says it i dont have a switch.. hehe

**Comment by dievaa** [comment]
Hi pixelatedpic, were you able to discover the device first? If not, please have a look at the following documentation about how to respond to discovery directives so that Alexa can discover the endpoints associated with your smart home skill: https://developer.amazon.com/de-DE/docs/alexa/device-apis/alexa-discovery.html#directives

Please note that the discovery process can potentially fail because of a mismatch between the account's PFM (Preferred market place), the skill locale, and the lambda endpoint region.

You can find additional information here: https://developer.amazon.com/en-US/blogs/alexa/device-makers/2023/07/smart-home-discovery-alexa-july-2023

**Comment by dievaa** [comment]
Hi pixelatedpic, were you able to discover the device first? If not, please have a look at the following documentation about how to respond to discovery directives so that Alexa can discover the endpoints associated with your smart home skill: https://developer.amazon.com/de-DE/docs/alexa/device-apis/alexa-discovery.html#directives

Please note that the discovery process can potentially fail because of a mismatch between the account's PFM (Preferred market place), the skill locale, and the lambda endpoint region.

You can find additional information here: https://developer.amazon.com/en-US/blogs/alexa/device-makers/2023/07/smart-home-discovery-alexa-july-2023
